name: 'Snapshot publish'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  fileVersion:
    required: false
    description: 'file version'
    default: 'package.json'
runs:
  using: node16
  main: dist/main.js
    

