name: 'test-snapshot-version-generation'
on:
  push
  # pull_request:
  # push:
  #   branches:
  #     - main
  #     - 'releases/*'

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    outputs:
      snapshot: ${{steps.action.outputs.snapshot}}
    steps:
      - uses: actions/checkout@v3
      # # uncomment to not push dist folder for each iteration testing
      # - run: npm install
      # - run: npm run package
      - uses: ./
        id: action
        with:
          fileVersion: 'package.json'
  printOuput:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - env:
          SNAPSHOT: ${{needs.test.outputs.snapshot}}
        run: echo "$SNAPSHOT"
